[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov-config pyproject.toml {args:test/unit}"
test-installer = "pytest --no-cov {args:test/installer} -vvv"
typing = "mypy {args:src test}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

build-addon = "python scripts/build_addon.py {args}"

[[envs.all.matrix]]
python = ["3.9", "3.10", "3.11", "3.12"]

[envs.default.env-vars]
DEADLINE_ENABLE_DEVELOPER_OPTIONS="True"

[envs.installer.scripts]
build-installer = "python {root}/scripts/build_installer_cli.py --installer-source-path {root}/installer/DeadlineCloudForBlenderSubmitter.xml {args:}"

[envs.integ]
pre-install-commands = [
  "pip install -r requirements-integ-testing.txt -r requirements-testing.txt"
]

[envs.integ.scripts]
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m 'not gpu'"
test_submitters = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m submitter"
test_adaptors = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m adaptor"
test_gpu = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m gpu"

[envs.integ-ci]
pre-install-commands = [
  "pip install -r requirements-integ-testing.txt -r requirements-testing.txt"
]

[[envs.integ-ci.matrix]]
blender = ["4.5.4"]
python = ["3.11"]

[[envs.integ-ci.matrix]]
blender = ["4.2.12"]
python = ["3.11"]

[[envs.integ-ci.matrix]]
blender = ["5.0.1"]
python = ["3.11"]

[envs.integ-ci.env-vars]
BLENDER_VERSION = "{matrix:blender}"
BLENDER_TEMP_ALLOWLIST = "{root}"

[envs.integ-ci.scripts]
setup = "python ./pipeline/setup-runner.py --versions {matrix:blender} --python-version {matrix:python} {args}"
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1"

[envs.codebuild.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"

[envs.release]
detached = true

[envs.release.scripts]
deps = "pip install -r requirements-release.txt"
bump = "semantic-release -v --strict version --no-push --no-commit --no-tag --skip-build {args}"
version = "semantic-release -v --strict version --print {args}"

[envs.docs]
dependencies = [
  "mkdocs>=1.5.0",
  "mkdocs-material>=9.4.0",
]

[envs.docs.scripts]
build = "mkdocs build"
serve = "mkdocs serve"
deploy = "mkdocs gh-deploy --force"