name: "Build Installers"

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  BuildLinuxInstaller:
    if: (github.repository == 'aws-deadline/deadline-cloud-for-blender')
    name: Build Linux Installer
    uses: aws-deadline/.github/.github/workflows/reusable_build_installers.yml@mainline
    secrets: inherit
    with:
      environment: ${{inputs.environment}}
      tag: ${{inputs.tag}}
      oses: "['Linux']"
