name: Label New Pull Requests

on:
    pull_request:
        types: [opened, reopened]

jobs:
    label-new-prs:
        uses: aws-deadline/.github/.github/workflows/reusable_label_new_prs.yml@mainline
        secrets: inherit