name: "Release: Publish"
run-name: "Release: ${{ inputs.tag }}"

on:
  workflow_dispatch:
      inputs:
          tag:
              required: true
              type: string

jobs:
  CheckForRelease:
    runs-on: ubuntu-latest
    name: CheckForRelease
    outputs:
      isReleased: ${{steps.checkrelease.outputs.isReleased}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: ${{inputs.tag}}
          fetch-depth: 0
      - id: checkrelease
        shell: bash
        run: |
          if gh release view "${{inputs.tag}}" &> /dev/null; then
            echo "isReleased=true" >> $GITHUB_OUTPUT
          else
            echo "isReleased=false" >> $GITHUB_OUTPUT
          fi
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease:
      needs: CheckForRelease
      if: needs.CheckForRelease.outputs.isReleased == 'false'
      uses: aws-deadline/.github/.github/workflows/reusable_prerelease.yml@mainline
      secrets: inherit
      with:
          installer_oses: "['Linux', 'Windows', 'MacOS']"
          tag: ${{inputs.tag}}
  release:
      needs: prerelease
      uses: aws-deadline/.github/.github/workflows/reusable_release.yml@mainline
      secrets: inherit
      with:
          tag: ${{inputs.tag}}
  IsCondaReady:
    needs: release
    runs-on: ubuntu-latest
    environment: release
    name: “Is the Conda Package available in all ProdWaves and have you ran any required manual tests?”
    steps:
      - run: |
         :
  publish:
      needs: IsCondaReady
      uses: aws-deadline/.github/.github/workflows/reusable_publish_python.yml@mainline
      secrets: inherit
      with:
          tag: ${{inputs.tag}}
  # PyPI does not support reusable workflows yet
  # # See https://github.com/pypi/warehouse/issues/11096
  PublishToPyPI:
      needs: publish
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade hatch
      - name: Build
        run: hatch -v build
      # # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

