name: "Close stale issues"

# Controls when the action will run.
# Run once a day at noon.
on: 
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v3
      with:
        # Setting messages to an empty string will cause the automation to skip
        stale-issue-message: 'Greetings!'
        # that category
        stale-pr-message: 'This pull request is in the review stage. It has been 2 weeks with no response to feedback provided by the maintainers. Please comment with an update to indicate work you are still working on the pull request. Thanks!'

        # These labels are required
        stale-issue-label: closing-soon
        exempt-issue-labels: awaiting-approval
        stale-pr-label: no-pr-activity
        exempt-pr-labels: awaiting-approval
        response-requested-label: response-requested

        # Don't set this to not apply a label when closing issues
        closed-for-staleness-label: closed-for-staleness

        # Issue timing
        days-before-stale: 14
        days-before-close: 14

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        #loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        #dry-run: true